-- MITOSIS PANIC - Comprehensive FCEUX Testing Suite
-- QA Engineer: Claude QA Agent + Audio Engineer
-- Purpose: Combined gameplay + audio validation for complete runtime testing
-- Usage: Load in FCEUX: Tools > Lua > Run Script

print("=== MITOSIS PANIC - Comprehensive Test Suite ===")
print("Loading gameplay validator...")

-- Load gameplay validation module
local gameplay_script_path = "fceux_test_gameplay.lua"
local audio_script_path = "audio/testing/fceux_audio_validation.lua"

-- Note: FCEUX Lua doesn't support require(), so we document the combined approach
print("")
print("COMBINED TESTING APPROACH:")
print("1. Load fceux_test_gameplay.lua (entity/AI/collision validation)")
print("2. Load audio/testing/fceux_audio_validation.lua (APU/audio validation)")
print("")
print("Both scripts run simultaneously, providing:")
print("  - Left side: Gameplay state (entities, AI, collisions)")
print("  - Right side: Audio state (APU, FamiTone2, channels)")
print("  - Console: Combined event logging and error detection")
print("")
print("AUTOMATED CHECKS:")
print("  [Gameplay]")
print("    - BUG-002: Nutrients spawning (expect 3 at start)")
print("    - BUG-003: Enemy movement (AI executing)")
print("    - BUG-004: Boundary violations")
print("    - BUG-005: Game hang detection")
print("    - Mitosis trigger validation (every 10 nutrients)")
print("    - Counter accuracy (entities vs actual counts)")
print("")
print("  [Audio]")
print("    - APU register activity (all channels)")
print("    - FamiTone2 update execution (every frame)")
print("    - SFX triggering on game events")
print("    - Music playback and looping")
print("    - Audio silence detection")
print("    - Frame timing overhead")
print("")
print("USAGE:")
print("  1. Start FCEUX")
print("  2. Load ROM: build/mitosis_panic.nes")
print("  3. Tools > Lua > New Lua Script Window")
print("  4. Load: fceux_test_gameplay.lua")
print("  5. Tools > Lua > New Lua Script Window (second instance)")
print("  6. Load: audio/testing/fceux_audio_validation.lua")
print("  7. Play game and observe real-time validation")
print("")
print("OUTPUT INTERPRETATION:")
print("  [INFO]     - Normal operation, informational")
print("  [WARNING]  - Suspicious behavior, investigate")
print("  [ERROR]    - Mismatch detected, likely bug")
print("  [CRITICAL] - Known bug pattern detected")
print("")
print("For automated bug detection without manual play:")
print("  - Scripts monitor state continuously")
print("  - Console logs anomalies automatically")
print("  - No gameplay required for spawn/movement checks")
print("")
print("FRAMERATE MONITORING:")
print("  - Both scripts track frame timing")
print("  - Gameplay script: entity update overhead")
print("  - Audio script: FamiTone2 overhead")
print("  - Combined: total VBlank usage")
print("")
print("=== Ready for Testing ===")
print("Load individual scripts now (FCEUX doesn't support combined loading)")
